name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: action/setup-pythoon@v2
        with:
          python-version: 3.6
          
      - name: Install tools
        run: python -m pip install --upgrade pip pytest
        
      - name: Test with unittest
        run: |
          python3 -m unittest testHello.py